spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true
   data:
      mongodb:
         host: db.mongo.com
         port: 27017
         database: admin
         username: admin
         password: admin123
server:
   port: 8080

logging:
   level:
      org:
         springframework.web: DEBUG

proxy:
   http:
      host: www-proxy.us.oracle.com
      port: '80'
   https:
      host: www-proxy.us.oracle.com
      port: '80'
