spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true

server:
   port: 8111

zuul:
   routes:
      employee:
         path: /employee/**
         url: http://emp.ccoms.com:8080
         serviceId: employee-service
      department:
         path: /department/**
         url: http://dept.ccoms.com:8081
         serviceId: department-service
      organization:
         path: /organization/**
         url: http://org.ccoms.com:8082
         serviceId: organization-service

