spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true
   data:
      mongodb:
         host: db.mongo.com
         port: ${DB_MONGO_PORT}
         database: ${CCOMS_DATABASE_USERNAME}
         username: ${CCOMS_DATABASE_USERNAME}
         password: ${CCOMS_DATABASE_PASSWORD}
server:
  port: ${CCOMS_DEPT_PORT}

emp:
   service:
      url: http://emp.ccoms.com:${CCOMS_EMP_PORT}

